# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-3.0-or-later
version = 1
SPDX-PackageName = "Talk iOS App"
SPDX-PackageSupplier = "Baitshook <https://www.baitshook.com/>"
SPDX-PackageDownloadLocation = "https://github.com/arshadkhan5/Baitshook-talk-ios/"

[[annotations]]
path = [".gitmodules", "Podfile"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["GccTalk/Images.xcassets/AppIcon.appiconset/*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Nextcloud GmbH"
SPDX-License-Identifier = "LicenseRef-NextcloudTrademarks"

[[annotations]]
path = ["GccTalk/Images.xcassets/twitter.imageset/twitter*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "X Corp."
SPDX-License-Identifier = "LicenseRef-XTrademarks"

[[annotations]]
path = ["GccTalk/Images.xcassets/*.imageset/Contents.json", "GccTalk/Images.xcassets/AppIcon.appiconset/Contents.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019-2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"


[[annotations]]
path = ["GccTalk/*.lproj/*.strings", "GccTalk/*.lproj/*.stringsdict"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Nextcloud translators"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [".pyspelling.wordlist.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["ThirdParty/AppRTC/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2014-2017 The WebRTC Project Authors. All rights reserved."
SPDX-License-Identifier = "BSD-3-Clause"
